name: deploy

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              env:
                  ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
              run: |
                  cd frontend
                  npm install
                  npm run build
                  cp -r dist ../backend/dist
                  cd ../backend
                  echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
                  npm install

            - name: Deploy code
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.TENCENT_HOST }}
                  username: ${{ secrets.TENCENT_USERNAME }}
                  key: ${{ secrets.TENCENT_KEY }}
                  port: ${{ secrets.TENCENT_PORT }}
                  source: "backend"
                  target: "~/code-runner"

            - name: Start the server
              uses: appleboy/ssh-action@master
              env:
                  PORT: ${{ secrets.SERVICE_PORT }}
              with:
                  host: ${{ secrets.TENCENT_HOST }}
                  username: ${{ secrets.TENCENT_USERNAME }}
                  key: ${{ secrets.TENCENT_KEY }}
                  port: ${{ secrets.TENCENT_PORT }}
                  timeout: 1m
                  command_timeout: 1m
                  script_stop: true
                  envs: PORT
                  script: |
                      lsof -ti:"$PORT" | if [ $(wc -w) -gt 1 ]; then kill -9 $(lsof -ti:"$PORT"); fi
                      cd ~/code-runner/backend
                      nohup node index.js > output.log 2>&1 &
